In [1]:
import numpy as np

In [2]:
# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


In [4]:
# matrix addition
addition = A + B
print("Addition:\n", addition)

Addition:
 [[ 6  8]
 [10 12]]


In [6]:
# matrix substraction
subtraction = A - B
print("Subtraction:\n", subtraction)

Subtraction:
 [[-4 -4]
 [-4 -4]]


In [7]:
# matrix multiplication
multiplication = np.dot(A, B)
print("Multiplication:\n", multiplication)

Multiplication:
 [[19 22]
 [43 50]]


In [9]:
# transpose
transpose_A = A.T
print("Transpose of A:\n", transpose_A)

Transpose of A:
 [[1 3]
 [2 4]]


In [10]:
# determinant
determinant_A = np.linalg.det(A)
print("Determinant of A:", determinant_A)

Determinant of A: -2.0000000000000004


In [ ]:
### Insights and Observations
- The Matrix Operations Tool was implemented using Python and NumPy.
- It supports addition, subtraction, multiplication, transpose, and determinant calculation.
- This task demonstrates basic numerical computing and matrix manipulation using NumPy.